markdown: kramdown
kramdown:
  math_engine: mathjax
permalink: pretty
include:
  - "**/*.md"
  - "**/*.markdown"
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
plugins:
  - jekyll-optional-front-matter