name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  # Allow manual trigger
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Install
        uses: pandoc/actions/setup@v1
        with:
          version: 3.6.3

      - name: Build static website
        run: |
          chmod +x ./generate_website.sh
          ./generate_website.sh
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./Mechanics_Website

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4